### ISSUE TITLE
Improve commit messages for better project tracking and changelogs

### ISSUE THREAD

**Issue by diasdavid** [ipfs/community#145]
One of the proposed ideas during the past two weeks (including the IPFS workshop) was to improve the quality of the commit messages across the IPFS projects, so that it becomes easier to manage and track progress + generate change logs.

To ensure that this gets adopted across projects, we must:
- [x] Research best practices and understand what are the best ones to adopt
- [x] Write guidelines for this purpose
- [x] Review PR to make sure they follow the guidelines
- [x] Generate the Changelogs

In an ideal case, the changelog generation can be even an automatic step of the release process.

Good reading: [`The Art of the Commit`](http://alistapart.com/article/the-art-of-the-commit)

**Comment by diasdavid** [comment]
tooling: https://github.com/dignifiedquire/aegir/issues/30

**Comment by haadcode** [comment]
I like the commit message guidelines Electron has: https://github.com/electron/electron/blob/master/CONTRIBUTING.md

And as a general reading, I found this to be a good capture of all the things: http://chris.beams.io/posts/git-commit/

**Comment by dignifiedquire** [comment]
We have merged the commit message guidelines, next steps are enforcing them and merging the changelog generation into aegir.

**Comment by diasdavid** [comment]
👏 👏 👏 👏 👏 👏 👏 👏 

For reference https://github.com/ipfs/community/blob/master/js-commit-guidelines.md
