### ISSUE TITLE
Set milestones for IPSchool Learning Materials & "How to Host" docs

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/community#161]
Set some milestones (in this ipfs/community repo) for 
- [x] Outlining a curriculum for learning about IPFS-related topics (@flyingzumwalt)
- [x] Assembling workshop material that can be used at nodeschool-style in-person workshops (@flyingzumwalt)
- [x] Assembling docs on how to host a workshop or meetup (@RichardLitt)
