### ISSUE TITLE
jsLand.next()

### ISSUE THREAD

**Issue by diasdavid** [ipfs/community#253]
> As part of every quarter planning, we sit down and have a discussion covering topics like tooling, codestyle, libraries and other things that affect the development of JS libraries overall. These topics are picked based on the interest that the community has shown.

Here are the ones we covered this quarter and the decisions we made converted in actionable tasks:

- [ ] Add a CONTRIBUTING.md to every repo that points to our JavaScript and Commit guidelines. https://github.com/ipfs/community/issues/241
- [ ] Update the JS guidelines to reflect latests standards https://github.com/ipfs/community/issues/225
- [x] Cancel the Greenkeeper for the time being until we have an option to make it less noisy and also, less resource intense on the CI side https://github.com/ipfs/community/issues/197
- [x] Switch use only Browser testing in Circle (Chrome) and Travis (Firefox), dropping SauceLabs for now.
- [x] Investigate the current % of users in each Node.js version, define what is our strategy with regards to supporting different versions.
- [x] Update the README of js-ipfs to communicate that we don't fully support Node.js 4 at the moment, see more at https://github.com/ipfs/js-ipfs/issues/781
  - [x] Invest time in upgrading the eth-package that is causing the limitation for Node.js 4 support. (more in https://github.com/ipfs/js-ipfs/issues/781
- [ ] Everyone showed interest in using Yarn, however, it is currently blocked until we have full Node.js 4 support. Close the PR to add it as it is out of date already
- [x] Move aegir to the IPFS org
- [x] Stub out desired aegir API and invite the community to help get this essential tool better for the whole development.

**Comment by diasdavid** [comment]
Linking here the usage of yarn comment: https://github.com/ipfs/js-ipfs-bitswap/pull/142#issuecomment-324649837

And the log from IRC convo:

```
15:27 <@victorbjelkholm> daviddias: sorry for kidnapping the dht PR! saw multiple places where we added yarn.lock and commented in the one where my thought popped up
15:28 <@daviddias> Can you bring that up to the issue on the community?
15:28 <@daviddias> And also list where you found it?
15:28 <@victorbjelkholm> strangely, reinstalled node (8.1.4) and now npm is working fine again seemingly
15:29 <@victorbjelkholm> daviddias: we had consensus on moving to yarn already no? Echoing dignifiedquire's comment in the mentioned PR
15:30 <@daviddias> Well, 6 months ago when npm5 never worked
15:30 <@daviddias> do we want to reconsider that to avoid having to get people to use another package manager?
15:30 <@daviddias> We will have the chance to discuss that in about 3 weeks
15:30 <@daviddias> I've been actively testing npm5 to be able to give good input there
15:32 <@victorbjelkholm> ah, sounds fair. I'll open a issue
```

My proposal on Yarn vs npm5. Let's wait to chat again in 3 weeks, a lot of time has passed. I've been using npm5 and so far not seeing issues anymore. I'm not particularly against using another package manager, just would really prefer to avoid asking the users to install yet another package manager. If the consensus in 3 weeks is yarn, so be it :) Let's just avoid spending our time in refactoring and bikeshed ;)

**Comment by diasdavid** [comment]
Also, thank you for self assigning yourself to the remaining items on this issue, @VictorBjelkholm 🌟

**Comment by dignifiedquire** [comment]
Proposal: Get some paid containers on CircleCI and stop using travis for javascript projects. At this point travis is just too unreliable and too slow for being an actual help. Ref https://github.com/ipfs/js-ipfs-bitswap/pull/142

**Comment by diasdavid** [comment]
Adding: 

- [ ] Explain linting decisions on the contributor Guidelines (ref: https://github.com/ipfs/aegir/issues/45)

**Comment by diasdavid** [comment]
Adding:

- [ ] Explain Perf Best Practices and guide (ref: https://github.com/dignifiedquire/borc/issues/6)
