### ISSUE TITLE
Issue Tracking Board

### ISSUE THREAD

**Issue by dylanPowers** [ipfs/community#7]
Looking at waffle.io. It looks very promising. I played around with the multi-repo linking which isn't perfect but it works. ~~I'm currently waiting upon the creation of ipfs/ipfs to act as a root repo for the IPFS projects.~~
Tasks for https://waffle.io/ipfs/ipfs:
- [ ] Get me permissions to ipfs/ipfs
- [ ] Link other repos to ipfs/ipfs
- [ ] Figure out how to prioritize issues/decrease noise

**Comment by dylanPowers** [comment]
I just realized this issue would probably fit better under https://github.com/ipfs/infrastructure

**Comment by jbenet** [comment]
yep! feel free to move it

**Comment by dylanPowers** [comment]
Moved to https://github.com/ipfs/infrastructure/issues/7
