### ISSUE TITLE
32c3 Adventure! - December 27-30 Hamburg 

### ISSUE THREAD

**Issue by Dignifiedquire** [ipfs/community#74]
Now that tickets are selling for [32c3](https://events.ccc.de/category/congress/32c3/). So let's discuss

**TODO: **
- [x] who is coming,
- [x] ~~do we want to create an IPFS Assembly~~(https://events.ccc.de/congress/2015/wiki/Static:Assemblies) 
- [ ] list any other planning like travel and meeting up
- [ ] all your great ideas

## IPFS Assembly

> We have an assembly, please comment and edit for corrections as I have no idea what I'm doing

https://events.ccc.de/congress/2015/wiki/Assembly:IPFS 

#### Add yourself to the Assembly

1. Create an account on https://events.ccc.de/congress/2015/wiki/
2. Edit your account and add IPFS as part of your activities, everyone is welcome! :D 
![image](https://cloud.githubusercontent.com/assets/1211152/11218323/677c5b78-8d4c-11e5-9962-9b65e6cee7aa.png)

**Comment by cryptix** [comment]
* [x] coming
* [x] :+1: Assembly might be nice to crash/meet/coordinate (hijacking the assemblies of other groups can be icky for this)

**Comment by Dignifiedquire** [comment]
I will setup the assembly as soon as I have an idea how many people are coming/willing to participate.

**Comment by diasdavid** [comment]
@Dignifiedquire updated your first post with more info, hope you don't mind :)

**Comment by lgierth** [comment]
I don't need a seat at the IPFS assembly, will be crashing with an assembly of friends, but I'll pop by every now and then :)

**Comment by whyrusleeping** [comment]
i'm planning on going

**Comment by RichardLitt** [comment]
Done! How do I find a place to sleep? Do we stay together? #confused

**Comment by diasdavid** [comment]
@RichardLitt for this type of event, it might be better to check lots of Airbnb and do pre reservations, stuff will be super booked if we leave it for last minute

**Comment by cryptix** [comment]
Check last years wiki for accommodations: https://events.ccc.de/congress/2014/wiki/Static:Accommodation

The congress slots for the hotel next door might be gone already but there are a lot of others options before falling back to airbnb.

**Comment by cryptix** [comment]
Ps: maybe also open a request on the talk page of the new wiki as well or ask on Twitter #32c3. I'm quite sure you can get a group deal somewhere.

**Comment by Dignifiedquire** [comment]
@RichardLitt there is also a large list already on the current wiki: https://events.ccc.de/congress/2015/wiki/Static:Accommodation if we are enough people we can also try to get a "Ferienwohnung" together (small flat for rent)

**Comment by jbenet** [comment]
Hey everyone, I submitted three talks to 32c3, all were rejected, no idea why. I sent an email asking for feedback, hopefully we'll get a response. 

Also, I'm 95%-sure not going; I have to be on the other side of the planet through xmas and new years'. Sorry! Have fun without me!

**Comment by diasdavid** [comment]
Al right, it is time to get our things together, when it comes to accommodation and travel, specially for folks that are coming from far. List of questions:

- [ ] Please add yourselves to https://events.ccc.de/congress/2015/wiki/Assembly:IPFS (you have to create an account for that), otherwise it is hard to be sure who is really going.
- [ ] Accommodation
- [ ] Flights
- [ ] New Year's, shall we spend New Years in Hamburg or Berlin?

**Comment by haadcode** [comment]
`New Year's, shall we spend New Years in Hamburg or Berlin?`

I'd recommend Berlin. Guaranteed it's a NYE you won't forget :)

Not sure if I'll make it to ccc but if you do end up staying in Berlin for NYE, I'd love to meet up with you all.

**Comment by whyrusleeping** [comment]
As for new years, i'm going to go with whatever the germans think will be the most fun

**Comment by Dignifiedquire** [comment]
Okay about accommodation, who needs something? Let's try to get a list together in the next 24h so we still have a chance of booking something decent.

I'll start with mine: Need 3 nights from 27-30th 

Re sylvester, I will be back in Freiburg for that I'm afraid, but from what I have Berlin sounds like the place to be.

**Comment by RichardLitt** [comment]
I've been taking a close look at my accounts and holiday plans, and I don't think I can make it this year. It's going to cost a fair penny to hop across the pond for me. Have fun, ya'll!

**Comment by lgierth** [comment]
> I'd recommend Berlin. Guaranteed it's a NYE you won't forget :)

What are you thinking about in particular? I've been living in Berlin for 6 years now and I can't say I've liked NYE here ;)

**Comment by haadcode** [comment]
`What are you thinking about in particular? I've been living in Berlin for 6 years now and I can't say I've liked NYE here ;)`

@lgierth didn't say it's necessarily likable, just... memorable ;) tbh, I've spent every (also 6) NYEs at home as there's a great view over an open area in Fhain, the fireworks - or the war zone if you will - are pretty amazing. 

I can't promise anything yet, but if there's a group coming, I'll consider throwing a party at my place for the ipfs folks :)

**Comment by diasdavid** [comment]
@haadcode let's get the IPFS NYE going, what can I do to help organize that? :)

**Comment by Dignifiedquire** [comment]
As things are getting closer, we should probably think also about things we need for the assembly. The only thing that I know for sure we will need are extension cables so everyone can get power. What else do we need? 

Also when is everyone arriving?

**Comment by diasdavid** [comment]
@Dignifiedquire we have a ton of equipment that we bought for CCCamp, @lgierth could you list what we have in place here so we know what we still need to buy?

**Comment by haadcode** [comment]
`@haadcode let's get the IPFS NYE going, what can I do to help organize that? :)`

@diasdavid unfortunately my travel schedule is a little tight around new year's and I won't have the time to organize a party. I'll be in Berlin, though, and would definitely like to hangout with you all.

**Comment by whyrusleeping** [comment]
I'll be arriving the morning of the event at 9:35 (so i'll probably be late), but the alternative is leaving on christmas and thats not super enticing.

**Comment by Dignifiedquire** [comment]
I'll be arriving in the night from the 26th to the 27th probably around 1am

**Comment by ralphtheninja** [comment]
I'll be around as well.

**Comment by nginnever** [comment]
landing in Hamburg @ 2:35pm on Sunday, I'll be in Berlin after 32c3 so +1 for the Brandenburg NYE

**Comment by diasdavid** [comment]
wooooo! nice :D 

I'll be in Hamburg by noon :)

**Comment by Dignifiedquire** [comment]
@diasdavid need the address and name of the place we are staying at. Also maybe we all share some mobile numbers for coordination?

**Comment by confiks** [comment]
I'll be around as well. Would love to talk a bit with you guys.

From IRC:

    Confiks: So there isn't already a lightning talk on 32C3 about IPFS, and the slots are 
             filling up pretty fast now.
    Confiks: So I've been bold, and have submitted a lightning talk here:
             https://events.ccc.de/congress/2015/wiki/Lightning:IPFS_-_The_Permanent,_Distributed_Web
    Confiks: Day 3 still had some slots, but the lightning talks take place during State of 
             the Onion and another Tor talk that will be highly popular. So desired timeframe 
             is now at the end of the lots at day 4.
    +lgierth: Confiks_: thanks! we submitted a few talks which weren't accepted, and didn't 
              actually think about a lightning talk yet
    +lgierth: good that you're keeping this option open for you or us
    Confiks: So this is just to reserve: I figure there are some good and knowledgable IPFS 
             speakers attending 32c3, and I would gladly give up the spot.
    Confiks: But if nobody else is, I'll give an introduction :)
    Kubuxu: Confiks_: that pdf that is linked looks really outdated.
    Confiks: Yeah, I know. I just submitted some slides.
    Confiks: And it's possible to send the final slides later. It's just so it won't be 
             rejected on the basis of 'no slides'.

**Comment by diasdavid** [comment]
@Dignifiedquire sent on the #32c3-assembly IRC channel :)

**Comment by lgierth** [comment]
Is anyone still waiting to get a ticket from me? If so, please tell me your email address, and I'll mail you the PDF which you have to show at the cash desk.

**Comment by ralphtheninja** [comment]
> Is anyone still waiting to get a ticket from me? If so, please tell me your email address, and I'll mail you the PDF which you have to show at the cash desk.

I have a buyer!

**Comment by ralphtheninja** [comment]
> Is anyone still waiting to get a ticket from me? If so, please tell me your email address, and I'll mail you the PDF which you have to show at the cash desk.

Oh or you meant a ticket for someone in the ipfs team?

**Comment by maxlath** [comment]
hello! I added the 32c3 Fahrplan to IPFS: https://gateway.ipfs.io/ipfs/QmZVpsk9M5WFU8XeciJHjhyEnAv4mmaMP4Ckss8H11Fqkd
Is there an IPFS assembly table somewhere? Would love to see what you folks are working on :)

**Comment by nginnever** [comment]
We hijacked a table by the bar that has Debian written on a piece of paper stuck to an empty bottle.

**Comment by cryptix** [comment]
Nice! Can you publish the URL rewrite script? The assets were still linked absolutely last time I tried to mirror.

**Comment by maxlath** [comment]
@cryptix well, I just used Sublime text "replace" features, folder by folder:
for html files in the root folder:
`href="/congress/2015/Fahrplan/` => `href="./`
`src="/congress/2015/Fahrplan/` => `src="./`
then for html files in subfolders:
`href="/congress/2015/Fahrplan/` => `href="../`
`src="/congress/2015/Fahrplan/` => `src="../`

That could definitely be done more efficiently by a script if repeated, but I thought that would be a one-shot, which it isn't given I have been told it was already outdated. Ideally, we should set an IPNS name to prevent having to change the url while being able to update it

**Comment by diasdavid** [comment]
We'll have an install party tomorrow 🎉🎉🎉

https://events.ccc.de/congress/2015/wiki/index.php?title=Session:IPFS_Install_Party_Extravaganza

**Comment by brimstone** [comment]
Good install party, despite the logistics!

**Comment by diasdavid** [comment]
Thank you for coming @brimstone :) 

Everyone, 32c3 was a lot of fun! Thank you for everyone that was present, we need to repeat again next year! Still processing all of the great conversations we had :) 

I wish everyone a very happy 2016!

**Comment by ralphtheninja** [comment]
:fireworks:
